### ISSUE TITLE
What's the evaluation script?

### ISSUE THREAD

**Issue by siddhantjain** [WangYueFt/dgcnn#1]
The readme refers to running evaluate.py, but I couldn't find the script. I am guessing I am missing something obvious here? Where should I find the evaluate.py script?

**Comment by gilsharo1** [comment]
Joining the question, can you add the evaluate.py script as well?

**Comment by salehjg** [comment]
I think with few modifications it's possible to use evaluation script of PointNet (evaluate.py)

here is a modified version that I use after training process:
[link to gist](https://gist.github.com/salehjg/39f8ce81b527c6d14e3ed1f09723860b
)

@siddhantjain @gilsharo1
