### ISSUE TITLE
concatenate features in classification model

### ISSUE THREAD

**Issue by zeal-up** [WangYueFt/dgcnn#10]
It seems that you did not mentioned that you concatenate feature in the first and second EdgeConv layer in your classification model. But in your code, it's appeared that the features output from the lower layer were
concatenate together.
```
 net = tf_util.conv2d(tf.concat([net1, net2, net3, net4], axis=-1), 1024, [1, 1], 
                       padding='VALID', stride=[1,1],
                       bn=True, is_training=is_training,
                       scope='agg', bn_decay=bn_decay)
```
I want to know that is it crucial for the classification results?

**Comment by wenbinTse** [comment]
Actually, I found the model architecture of this rep is quite different from what's described in the paper.

**Comment by wusuoweima** [comment]
I also found it. Can the authors give some explanation about it?
