### ISSUE TITLE
The code is running super slow?

### ISSUE THREAD

**Issue by Haiyan-Chris-Wang** [WangYueFt/dgcnn#11]
@WangYueFt @syb7573330 I could run the code successfully, but the code is running super slow. The speed is about 10 epochs/day. Do you have any idea about this problem or it is the normal speed for this code?

**Comment by WangYueFt** [comment]
Are you running on CPU? What's the GPU model if it's runing on GPU?

**Comment by Haiyan-Chris-Wang** [comment]
@WangYueFt Yeah, I found the problem. Now I have switched to the GPU (GTX 1080Ti), although It is faster than CPU, the speed is still slow, about 5 epochs/hour. So how fast is your running speed?

**Comment by WangYueFt** [comment]
I think that's roughly the same.

**Comment by Haiyan-Chris-Wang** [comment]
I see. Thanks for your reply!

**Comment by Haiyan-Chris-Wang** [comment]
@WangYueFt @syb7573330 Could you help me explain why do we need to perform tf.concat here to combine the previous net? It seems didn't mention in the paper.
https://github.com/WangYueFt/dgcnn/blob/29948ad95d2e8843de542fae910a7f495f549160/models/dgcnn.py#L79

**Comment by KangchengLiu** [comment]
@Haiyan-Chris-Wang How did you switch to GPU？
