### ISSUE TITLE
why do we need net = tf_util.conv2d(tf.concat([net1, net2, net3, net4], axis=-1), 1024, [1, 1], ?

### ISSUE THREAD

**Issue by Haiyan-Chris-Wang** [WangYueFt/dgcnn#13]
@WangYueFt @syb7573330 Could you help me explain why do we need to perform tf.concat here to combine the previous net? It seems didn't mention in the paper.

Also does anyone understands this line? Please help

https://github.com/WangYueFt/dgcnn/blob/29948ad95d2e8843de542fae910a7f495f549160/models/dgcnn.py#L79

**Comment by WangYueFt** [comment]
Hi,

I think we mentioned in the paper that skip connections are used. It
roughly helps combining features from different scales

Best,
Yue

**Comment by Haiyan-Chris-Wang** [comment]
@WangYueFt Thanks for your reply! Just one more question, I find that you compare the result with baseline in the paper. As you mentioned, the baseline is using fixed knn graph rather dynamic graph. So could you help me explain what is the difference between fixed knn graph and dynamic knn graph?

**Comment by Haiyan-Chris-Wang** [comment]
@WangYueFt @syb7573330 From my understanding, the fixed knn graph means that you only calculate the adjacent matrix once while for the dynamic graph, the adjacent matrix is different for each layer. Is that right?
