### ISSUE TITLE
the difference between fixed knn graph and dynamic knn graph?

### ISSUE THREAD

**Issue by Haiyan-Chris-Wang** [WangYueFt/dgcnn#14]
@WangYueFt  I find that you compare the result with baseline in the paper. As you mentioned, the baseline is using fixed knn graph rather dynamic graph. So could you help me explain what is the difference between fixed knn graph and dynamic knn graph?

**Comment by WangYueFt** [comment]
Hi,

Yes, the baseline is using fixed graph. The fixed graph is computed based
on the positions of points while the dynamic graph is computed based on the
distance in feature space in corresponding layers.

Best,
Yue

**Comment by Haiyan-Chris-Wang** [comment]
@WangYueFt Does that mean for the fixed graph, you only calculate the graph (edge feature) for the input (at the beginning of the network), but for the dynamic, you need to calculate the graph layer by layer?

**Comment by WangYueFt** [comment]
Yes. I believe that’s correct

**Comment by Haiyan-Chris-Wang** [comment]
Thanks so much for your kind help!

**Comment by WangYueFt** [comment]
No problem!
