### ISSUE TITLE
Visualization for part segmentation

### ISSUE THREAD

**Issue by FrankCAN** [WangYueFt/dgcnn#15]
Hi,
Is there anyone who knows how to visualize the results of part segmentation? Many thanks for your help.

Best Regards
Frank

**Comment by shengrongjin** [comment]
I have the same question !

**Comment by syb7573330** [comment]
We used Unity to render our results. We simply load the points into the scene, and instantiate each point as a sphere with a proper radius. We set the color of each point using some predefined color codes for different categories.
