### ISSUE TITLE
Point cloud transform block different from paper

### ISSUE THREAD

**Issue by patrick-llgc** [WangYueFt/dgcnn#16]
Hi!

Thanks for sharing the code. I am reading the [paper](https://arxiv.org/pdf/1801.07829.pdf) and found that the implementation of the point cloud transform block (aka T-Net in the original point net paper) is different from what is mentioned in the [code](https://github.com/WangYueFt/dgcnn/blob/master/models/transform_nets.py#L27).

In the paper, as shown in Fig. 3, the coordinate difference the k nearest neighbor and the coordinates of the point is concatenated (therefor n x k x (3+3) = n x k x 6). 

However in the code, there is one additional max pooling along the number of points axis, as compared to the [original point net implementation](https://github.com/charlesq34/pointnet/blob/master/models/transform_nets.py#L10). I do not quite understand why.

If someone can enlighten me or share their thought on this, I would be very grateful.

**Edit**: 
I think I figured out why the input of the t-net is n x k x 6 as the input already went through feature transformation defined [here](https://github.com/WangYueFt/dgcnn/blob/master/models/dgcnn.py#L29). However I am still puzzled by the additional max pooling operation as compared to the original point net implementation.

**Comment by WangYueFt** [comment]
> Hi!
> 
> Thanks for sharing the code. I am reading the [paper](https://arxiv.org/pdf/1801.07829.pdf) and found that the implementation of the point cloud transform block (aka T-Net in the original point net paper) is different from what is mentioned in the [code](https://github.com/WangYueFt/dgcnn/blob/master/models/transform_nets.py#L27).
> 
> In the paper, as shown in Fig. 3, the coordinate difference the k nearest neighbor and the coordinates of the point is concatenated (therefor n x k x (3+3) = n x k x 6).
> 
> However in the code, there is one additional max pooling along the number of points axis, as compared to the [original point net implementation](https://github.com/charlesq34/pointnet/blob/master/models/transform_nets.py#L10). I do not quite understand why.
> 
> If someone can enlighten me or share their thought on this, I would be very grateful.
> 
> **Edit**:
> I think I figured out why the input of the t-net is n x k x 6 as the input already went through feature transformation defined [here](https://github.com/WangYueFt/dgcnn/blob/master/models/dgcnn.py#L29). However I am still puzzled by the additional max pooling operation as compared to the original point net implementation.

We initially wanted to use EdgeConv in the spatial transformer as we did for the main backbone.
