### ISSUE TITLE
Do we need multiple GPUs?

### ISSUE THREAD

**Issue by usherbob** [WangYueFt/dgcnn#17]
For ModelNet-40 classification task, how long do you guys need to run one epoch? On my PC, it took about 5 hours for 15 epochs with a Tesla k40c card. Do I need to use 2 or 3 GPUs to speed it up?

**Comment by LiangRongguo** [comment]
I am using Tesla K80, and one epoch takes 20 minutes.
The code in line 27-29 of dgcnn.py is unused. I suppose maybe deleting those lines would speed up a little bit?

**Comment by usherbob** [comment]
Since I realized ModelNet-40 is not large, we may not need to use multiple GPUs. And my Tesla k40c is old, using Titan 1080 may accelerate the speed.
