### ISSUE TITLE
Questions About the classification of ModelNet40

### ISSUE THREAD

**Issue by wusuoweima** [WangYueFt/dgcnn#18]
1.  It seems that you did not mentioned that you concatenate feature in the first and second EdgeConv layer in your classification model. But in your code models/dgcnn.py, it's appeared that the features output from the lower layer were concatenate together. Then which way is accuracy 92.2%  obtained?
` net = tf_util.conv2d(tf.concat([net1, net2, net3, net4], axis=-1), 1024, [1, 1], 
                       padding='VALID', stride=[1,1],
                       bn=True, is_training=is_training,
                       scope='agg', bn_decay=bn_decay)`

2. ModelNet40 data set has two form: aligened and  unaligned. Which form is used in the paper DGCNN?

**Comment by WangYueFt** [comment]
> * It seems that you did not mentioned that you concatenate feature in the first and second EdgeConv layer in your classification model. But in your code models/dgcnn.py, it's appeared that the features output from the lower layer were concatenate together. Then which way is accuracy 92.2%  obtained?
>   ` net = tf_util.conv2d(tf.concat([net1, net2, net3, net4], axis=-1), 1024, [1, 1],  padding='VALID', stride=[1,1], bn=True, is_training=is_training, scope='agg', bn_decay=bn_decay)`
> * ModelNet40 data set has two form: aligened and  unaligned. Which form is used in the paper DGCNN?

1. Yeah, skip connection does help.
2. We use the same data with PointNet/PointNet++ paper.
