### ISSUE TITLE
Questions about the Input point cloud data dimension of the EdgeConv 

### ISSUE THREAD

**Issue by limt15** [WangYueFt/dgcnn#19]
Thank you very much for sharing the code！

I attempt to use to the dataset `ModelNet40 (XYZ and normal )`, which is 6 dimensions. when I changed the input_dim from `3` to `6`, but it doesn't work.
Are the input point cloud data dimensions of Dgcnn/EdgeConv fixed into `3` in the code and paper?
How can I use the `ModelNet40 (XYZ and normal )` with `6` input dimensions on Dgcnn/EdgeConv ?

Can you help me to solve this problem?
look forward to your reply！

**Comment by gabrielecaddeo** [comment]
Hi, did you try that?
