### ISSUE TITLE
Semantic segmentation: model differs from paper

### ISSUE THREAD

**Issue by laurimi** [WangYueFt/dgcnn#2]
Thanks for your code contribution! I read the paper, and noticed that the EdgeConv architecture (Figure 3) suggested for semantic segmentation is different from the one implemented in [the code](https://github.com/WangYueFt/dgcnn/blob/master/sem_seg/model.py). In particular, the code uses two parallel pooling operations (max and mean instead of only max). Could you tell which one was used to obtain the results in the paper, and perhaps comment on reasons for the difference? Was using both max and mean aggregation better than only using either one alone?

**Comment by zeal-up** [comment]
I have this issue too. And also, the segmentation model in your code is quite different from the paper. It seems that you only use edgeconv operation in the first mlp layer in each EdgeConv block for segmentation. While in the classification model, each mlp layer in EdgeConv block do the edgeconv operation.
And the concatenation operation is different from the paper.
@WangYueFt 
Sorry to interrupt you, I just make sure that I did not understand it wrong.

**Comment by WangYueFt** [comment]
Hi,

Yes. The concatenation is different from what is in the paper. We will release the code exactly the same with the paper. Stay tuned!

Best,
Yue
