### ISSUE TITLE
An issue about the pairwise_distance

### ISSUE THREAD

**Issue by sailor-z** [WangYueFt/dgcnn#20]
Hi,
Thanks for releasing the code. I have an issuse about the estimation of "pairwise_distance".  In some previous works, the k nearest neighbors are estimated by Euclidean distance such as |x - xi|.  I'm confused about the implemention of "pairwise_distance", -i.e., "-xx - inner - xx.transpose(2, 1)". Could you please do me a favor?

Best regards

**Comment by emedinac** [comment]
Hi maybe I can give you an inside, it's like a math notation.  But means the same

-||x_i - x_j||^2 = -||x_i||^2 + 2Re(x_i , x_j) - ||x_j||^2 , where Re is the inner product.
He is taking the largest values of the negative distances, this implementation is more efficient (in memory maybe) than the expression you mentioned. You also can performed something like this:
X(:,:,None) - X(:,None) you will have the same result,  theoretically. Not sure about the precision  in the floating points or memory consumption.

**Comment by sailor-z** [comment]
> Hi maybe I can give you an inside, it's like a math notation. But means the same
> 
> -||x_i - x_j||^2 = -||x_i||^2 + 2Re(x_i , x_j) - ||x_j||^2 , where Re is the inner product.
> He is taking the largest values of the negative distances, this implementation is more efficient (in memory maybe) than the expression you mentioned. You also can performed something like this:
> X(:,:,None) - X(:,None) you will have the same result, theoretically. Not sure about the precision in the floating points or memory consumption.

**Comment by sailor-z** [comment]
I got it. Thank you so much!
