### ISSUE TITLE
accuracy of ModelNet40

### ISSUE THREAD

**Issue by rruixxu** [WangYueFt/dgcnn#22]
Hi, 
I read your paper uploaded to arxiv long time ago in which the accuracy of ModelNet40 was reported as 92.2%. However, the accuracy becomes 92.9% in your ACM Transaction paper. So, I read your most-recent code again and compare it with the code I downloaded before, but I could not figure out what has been changed. Could you declare what contributes to the 0.7% improvement?

Thanks.

**Comment by WangYueFt** [comment]
Hi,

Thank you for asking. The changes are:
1. Relu -> LeakyReLU
2. Step learning rate scheduler -> CosineScheduler
3. Num of channels changed in EdgeConv layers

Best,
Yue

**Comment by Yuquan-Lu** [comment]
> 嗨，谢谢你的提问。更改如下：1。Relu - > LeakyReLU 2.步进学习速率调度程序 - > CosineScheduler 3.在EdgeConv层中更改通道数最佳，悦
> [...](#)
> 2019年6月18日上午12:15，rruixxu ***@***.***>写道：谢谢您好，你方便将修改后的代码，给我参考一下吗？
