### ISSUE TITLE
PyTorch Implementation different with origin paper.

### ISSUE THREAD

**Issue by XuyangBai** [WangYueFt/dgcnn#24]
Hi, Thanks for your sharing. I have a question about your `get_graph_feature` function of pytorch implementaion.
```python
def get_graph_feature(x, k=20, idx=None):
    batch_size = x.size(0)
    num_points = x.size(2)
    x = x.view(batch_size, -1, num_points)
    if idx is None:
        idx = knn(x, k=k)   # (batch_size, num_points, k)
    device = torch.device('cuda')

    idx_base = torch.arange(0, batch_size, device=device).view(-1, 1, 1)*num_points

    idx = idx + idx_base

    idx = idx.view(-1)
 
    _, num_dims, _ = x.size()

    x = x.transpose(2, 1).contiguous()   # (batch_size, num_points, num_dims)  -> (batch_size*num_points, num_dims) #   batch_size * num_points * k + range(0, batch_size*num_points)
    feature = x.view(batch_size*num_points, -1)[idx, :]
    feature = feature.view(batch_size, num_points, k, num_dims) 
    x = x.view(batch_size, num_points, 1, num_dims).repeat(1, 1, k, 1)
    
    feature = torch.cat((feature, x), dim=3).permute(0, 3, 1, 2)
  
    return feature
```
I think the way you get the variable `feature` is different with the description in the paper. Here I think the feature is only `h_j` while in your paper you use `h_j - h_i` so you may do `feature = feature - x` before concatenation?

**Comment by WangYueFt** [comment]
> Hi, Thanks for your sharing. I have a question about your `get_graph_feature` function of pytorch implementaion.
> 
> ```python
> def get_graph_feature(x, k=20, idx=None):
>     batch_size = x.size(0)
>     num_points = x.size(2)
>     x = x.view(batch_size, -1, num_points)
>     if idx is None:
>         idx = knn(x, k=k)   # (batch_size, num_points, k)
>     device = torch.device('cuda')
> 
>     idx_base = torch.arange(0, batch_size, device=device).view(-1, 1, 1)*num_points
> 
>     idx = idx + idx_base
> 
>     idx = idx.view(-1)
>  
>     _, num_dims, _ = x.size()
> 
>     x = x.transpose(2, 1).contiguous()   # (batch_size, num_points, num_dims)  -> (batch_size*num_points, num_dims) #   batch_size * num_points * k + range(0, batch_size*num_points)
>     feature = x.view(batch_size*num_points, -1)[idx, :]
>     feature = feature.view(batch_size, num_points, k, num_dims) 
>     x = x.view(batch_size, num_points, 1, num_dims).repeat(1, 1, k, 1)
>     
>     feature = torch.cat((feature, x), dim=3).permute(0, 3, 1, 2)
>   
>     return feature
> ```
> 
> I think the way you get the variable `feature` is different with the description in the paper. Here I think the feature is only `h_j` while in your paper you use `h_j - h_i` so you may do `feature = feature - x` before concatenation?

Hi,

I have updated the implementation.

**Comment by XuyangBai** [comment]
Sorry but I do not understand what's your meaning. 

Like what you do in tensorflow version:
```python
edge_feature = tf.concat([point_cloud_central, point_cloud_neighbors-point_cloud_central], axis=-1)
```
Why  don't you munis the central point feature?

**Comment by WangYueFt** [comment]
> Sorry but I do not understand what's your meaning.
> 
> Like what you do in tensorflow version:
> 
> ```python
> edge_feature = tf.concat([point_cloud_central, point_cloud_neighbors-point_cloud_central], axis=-1)
> ```
> 
> Why don't you munis the central point feature?

Hi,

I have updated the a
