### ISSUE TITLE
There exist no rotation augmentation in the preprocess of the pytorch implementation 

### ISSUE THREAD

**Issue by linhaojia13** [WangYueFt/dgcnn#27]
Hi, thank you for opening your code.
I notice that there exist no rotation augmentation in the preprocess of the pytorch implementation , which is different with the tf implementation. However, the best accuracy achieve 93.1 .Does it means that the rotation augmentation is useless?
I want to construct a auto-encoder which use the dgcnn as the backbone of the encoder, therefore the absence of rotation augment in the modelnet classification really puzzle me. Does it mean that I needn't execute the rotation augment even though the dgcnn is used for reconstruction purpose which is different with classification?
Thanks a lot.

**Comment by WangYueFt** [comment]
> classification

I think that depends on your own application. For application that doesn't deal with rotation, I would not add rotation augmentation.
