### ISSUE TITLE
Questions about transform nets

### ISSUE THREAD

**Issue by usherbob** [WangYueFt/dgcnn#28]
Hello Yue,
I have a question about transform networks, How to devise a transform net? I noticed your transform net in tensorflow implementation is almost the same as in `charlesq/pointnet` implementation, while you use EdgeConv instead of 1x1 conv in your model.

**Comment by WangYueFt** [comment]
> Hello Yue,
> I have a question about transform networks, How to devise a transform net? I noticed your transform net in tensorflow implementation is almost the same as in `charlesq/pointnet` implementation, while you use EdgeConv instead of 1x1 conv in your model.

Yes. We initially wanted to use EdgeConv as we did for the backbone.
