### ISSUE TITLE
visualization problem

### ISSUE THREAD

**Issue by heng94** [WangYueFt/dgcnn#29]
Hi, 
  Thanks for sharing the work! I have some problem with visualization. how to visualize the results such as figure 4 in your paper
![image](https://user-images.githubusercontent.com/32918541/61921006-315e6f00-af8e-11e9-804d-95da0ca00e59.png)
Thanks a lot!

**Comment by WangYueFt** [comment]
> Hi,
> Thanks for sharing the work! I have some problem with visualization. how to visualize the results such as figure 4 in your paper
> ![image](https://user-images.githubusercontent.com/32918541/61921006-315e6f00-af8e-11e9-804d-95da0ca00e59.png)
> Thanks a lot!

We selected a seed point (in red) and computed l2 distances to it in feature space.
