### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by cl5220418** [WangYueFt/dgcnn#3]
> Traceback (most recent call last):
  File "train.py", line 285, in <module>
    train()
  File "train.py", line 234, in train
    train_one_epoch(sess, ops, train_writer)
  File "train.py", line 267, in train_one_epoch
    ops['pointclouds_phs'][1]: current_data[start_idx_1:end_idx_1, :, :],
IndexError: list index out of range

**Comment by tbarton16** [comment]
Hello @cl5220418 How did you solve this?  Was it a version issue?

**Comment by sumeshthakr** [comment]
Hi Tgere, 
I am getting the similar error,

Were you able to solve it?
