### ISSUE TITLE
Training with my own data

### ISSUE THREAD

**Issue by hongtaowu67** [WangYueFt/dgcnn#31]
Hi there,

Could you kindly provide the code for generating the pointcloud for training and testing?

I would like to train with my own data.

Thanks!

**Comment by WangYueFt** [comment]
> Hi there,
> 
> Could you kindly provide the code for generating the pointcloud for training and testing?
> 
> I would like to train with my own data.
> 
> Thanks!

It depends on the format of your data. You can use trimesh to extract point clouds from mesh or cad models.
