### ISSUE TITLE
How do you visualize the extracted features?

### ISSUE THREAD

**Issue by longmalongma** [WangYueFt/dgcnn#33]
How do you visualize the extracted features?Can you send me your code about visualization of extracted features?My email is that 1442342449@qq.com.Think you very much.

**Comment by WangYueFt** [comment]
> How do you visualize the extracted features?Can you send me your code about visualization of extracted features?My email is that [1442342449@qq.com.Think](mailto:1442342449@qq.com.Think) you very much.

We just use Matlab to compute the distance in feature space.
