### ISSUE TITLE
Dose knn neighbours xj include the center point xi?

### ISSUE THREAD

**Issue by wusuoweima** [WangYueFt/dgcnn#34]
In your paper: 
![image](https://user-images.githubusercontent.com/30040019/63737942-aa692300-c8ba-11e9-8e3c-635fd1a7c427.png)

![image](https://user-images.githubusercontent.com/30040019/63736385-6e7f8f00-c8b5-11e9-9dd3-23a4d0627959.png)

 dose knn neighbours xj 0r ![image](https://user-images.githubusercontent.com/30040019/63736273-18125080-c8b5-11e9-8e64-ad9dcdd5f534.png) include the center point xi in the paper and code?

**Comment by wusuoweima** [comment]
@WangYueFt

**Comment by WangYueFt** [comment]
> @WangYueFt

It does.
