### ISSUE TITLE
Undefined "weight_decay" in tensorflow/sem_seg/model.py

### ISSUE THREAD

**Issue by MrJimm** [WangYueFt/dgcnn#36]
Hi!
In tensorflow/sem_seg/model.py there seems to be undefined "weight_decay" variable used in tf_util.conv2d(...) layers while building model.

For example here:
` 
out1 = tf_util.conv2d(edge_feature, 64, [1,1],
padding='VALID', stride=[1,1],
bn=True, is_training=is_training, weight_decay=weight_decay,
scope='adj_conv1', bn_decay=bn_decay, is_dist=True)
`

**Comment by niallomahony93** [comment]
I came across the same issue, what value should it be?

**Comment by WangYueFt** [comment]
> Hi!
> In tensorflow/sem_seg/model.py there seems to be undefined "weight_decay" variable used in tf_util.conv2d(...) layers while building model.
> 
> For example here:
> ` out1 = tf_util.conv2d(edge_feature, 64, [1,1], padding='VALID', stride=[1,1], bn=True, is_training=is_training, weight_decay=weight_decay, scope='adj_conv1', bn_decay=bn_decay, is_dist=True)`

That could be caused by the tensor flow update. Can you use the old version of tensor flow?

**Comment by Dinghow** [comment]
You can just use the default value weight_decay=0.0, I don't think this issue is attributed to the version of tensorflow.
