### ISSUE TITLE
KeyError: "Unable to open object (object 'data' doesn't exist)"

### ISSUE THREAD

**Issue by hjsg1010** [WangYueFt/dgcnn#4]
Thanks for your awesome code share

I run the train.py code following readme step by step, but when I run python train.py, there is an error:KeyError: "Unable to open object (object 'data' doesn't exist)", here is details:

![image](https://user-images.githubusercontent.com/17421673/45404786-58c08c00-b69b-11e8-9115-cbf2b0539c13.png)

I solve all the problem of dependency but above error keep showing

I run the pointnet(https://github.com/charlesq34/pointnet) without error, however, I cannot run dgcnn...

please help me, so I can study about dgcnn more

sorry for my poor english skills

**Comment by WangYueFt** [comment]
Hi, it looks like h5 error. Can you maybe restart your computer and/or make sure the data is ready.

**Comment by hjsg1010** [comment]
> Hi, it looks like h5 error. Can you maybe restart your computer and/or make sure the data is ready.

Thanks for reply
![image](https://user-images.githubusercontent.com/17421673/45460546-472dc180-b739-11e8-8dc2-a00c6be21457.png)

I reboot my computer and checked data, however, same error keep occurs..
the data I used is same data that I used for pointnet(https://github.com/charlesq34/pointnet)
Should I change something?

**Comment by hjsg1010** [comment]
> > Hi, it looks like h5 error. Can you maybe restart your computer and/or make sure the data is ready.
> 
> Thanks for reply
> ![image](https://user-images.githubusercontent.com/17421673/45460546-472dc180-b739-11e8-8dc2-a00c6be21457.png)
> 
> I reboot my computer and checked data, however, same error keep occurs..
> the data I used is same data that I used for pointnet(https://github.com/charlesq34/pointnet)
> Should I change something?

or If you are ok, can you give link for download dataset? So I can try with same data as yours

**Comment by syb7573330** [comment]
Looks like your 'ply_data_train3.h5' and 'ply_data_train4.h5' are broken, can you try downloading them again?

**Comment by hjsg1010** [comment]
> Looks like your 'ply_data_train3.h5' and 'ply_data_train4.h5' are broken, can you try downloading them again?

Thx for reply,
I will try that

**Comment by hjsg1010** [comment]
> Looks like your 'ply_data_train3.h5' and 'ply_data_train4.h5' are broken, can you try downloading them again?

Wow, it works... Sorry for my mistake bothers you.
By the way, If I want to put my data in this model, what format file should I run in data_prep_util.py?
Should I make my file as .off format or other specific format?

**Comment by syb7573330** [comment]
I would recommend you to convert your point cloud data into the same format as the train/test dataset (.h5) provided by PointNet. But you are free to use any data format, as long as you eventually convert them into a 3D array of shape (batch_size, num_point, 3).

**Comment by hjsg1010** [comment]
> I would recommend you to convert your point cloud data into the same format as the train/test dataset (.h5) provided by PointNet. But you are free to use any data format, as long as you eventually convert them into a 3D array of shape (batch_size, num_point, 3).

Thank you very much for your quick and sincere reply.
And also I really learn a lot from your paper and codes. 
Thank you

**Comment by dvirginz** [comment]
@syb7573330 
Hi,
I have the same problem, i.e  
```
File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'data' doesn't exist)"
```
When you suggest to download the data again, how do you suggest doing that?
My steps were:
1) git clone
2) enter the folder
3) python train.py

where step 3 downloaded the data folder.
If I want, I can delete the data folder, and train.py will download it again, but the error keeps coming

This is the content I have in the folder prior to the crash
`(venv)XXXXX:~/dgcnn/data/modelnet40_ply_hdf5_2048$ ls
ply_data_test0.h5             ply_data_train0.h5             ply_data_train2.h5             ply_data_train_4_id2file.json
ply_data_test_0_id2file.json  ply_data_train_0_id2file.json  ply_data_train_2_id2file.json  shape_names.txt
ply_data_test1.h5             ply_data_train1.h5             ply_data_train3.h5             test_files.txt
ply_data_test_1_id2file.json  ply_data_train_1_id2file.json  ply_data_train4.h5             train_files.txt
`
Thanks a lot!

**Comment by thirdlastletter** [comment]
Hi,
I have been having the same error, even though when I try opening the hdf5 files individually it is possible to use the object 'data'. Has someone figured out a solution?
