### ISSUE TITLE
Categoryless Training/Testing for part segmentation

### ISSUE THREAD

**Issue by iKessho** [WangYueFt/dgcnn#42]
Hi,

Would like to ask if the DGCNN model is able to train/test without explicitly stating the category (e.g. plane, vase, mug) of the object/data. I've looked through the source code and i found that you have to explicitly indicate the category of the object before it is able to segment it.

Also if its able to achieve segmentation of N parts. The current implementation seems to have hard coded the number of parts for each category. I'm wondering if its able to achieve something similar to this [https://www.youtube.com/watch?v=6JQdNzsw7jA](url)

**Comment by WangYueFt** [comment]
You don't need to. You can remove the branch that takes the class label.
