### ISSUE TITLE
No such file or directory: 'pretrained/model.2048.t7'

### ISSUE THREAD

**Issue by antao97** [WangYueFt/dgcnn#46]
I tried to run your script under pytorch, but there is no pretrained model for model.2048.t7.

**Comment by amiltonwong** [comment]
Hi, @WangYueFt ,

It's confirmed that [pretrained](https://github.com/WangYueFt/dgcnn/tree/master/pytorch/pretrained) doesn't contain file `model.2048.t7`. Please help to upload it.

THX!

**Comment by byliut** [comment]
I got the same problem

**Comment by antao97** [comment]
@amiltonwong @byliut 
You can refer to https://github.com/AnTao97/dgcnn.pytorch for `model.2048.t7`
