### ISSUE TITLE
Serious problem. About label smoothing in loss

### ISSUE THREAD

**Issue by a18700** [WangYueFt/dgcnn#49]
While examining provided codes,

I found out label smoothing term is applied for cross entroy loss.

However, there is no description about that in the paper.

I doubt for the effects of this term.. Is there any official results without label smoothing term

**Comment by a18700** [comment]
I've experimented without label smoothing, and found out performance is hugely deterior to paper's.
I think this should be clarified...

Maybe i think it's possible that performance of reported dgcnn is from effects of label smoothing, not a virtue of architectural innovations.

**Comment by WangYueFt** [comment]
> I've experimented without label smoothing, and found out performance is hugely deterior to paper's.
> I think this should be clarified...
> 
> Maybe i think it's possible that performance of reported dgcnn is from effects of label smoothing, not a virtue of architectural innovations.

Hi,

Are you running the pytorch code? I re-run the code without label smoothing and the result is very close.
