### ISSUE TITLE
preparing .h5 format data 

### ISSUE THREAD

**Issue by hjsg1010** [WangYueFt/dgcnn#5]
Hi @WangYueFt @syb7573330 

Answers for former issues I wrote helped me a lot.

Now, I am trying to apply your model using my data.

I have (x,y,z) for point cloud and also I have mesh data.

I understand that to using pointnet or dgcnn, the file for input is .h5 file for points.

I really searched a lot for making .h5 file, but I failed.

What I am trying to do is,
1. prepare points data.( such as .obj, .off, .pts)
2. change data into .ply
3. .ply -> .h5
 is it right? 

Could you notice me some example codes for upper case ? 

------------------------------
the code I tried:
https://github.com/charlesq34/pointnet/blob/master/utils/data_prep_util.py
https://github.com/IsaacGuan/PointNet-Plane-Detection/tree/master/data

-----------------------------

sorry for my poor english skills
This issue may seem very stupid, but I would appreciate it if you could help it.

**Comment by Leerw** [comment]
Have you got the solution? @ @hjsg1010
