### ISSUE TITLE
python collect_indoor3d_data.py ERROR

### ISSUE THREAD

**Issue by hjsg1010** [WangYueFt/dgcnn#57]
I'm trying "python collect_indoor3d_data.py" 

However, it occur ERROR message.

I don't know why it happens.. 

can you help me?

**Comment by WangYueFt** [comment]
> I'm trying "python collect_indoor3d_data.py"
> 
> However, it occur ERROR message.
> 
> I don't know why it happens..
> 
> can you help me?

What error message do you get?
