### ISSUE TITLE
How do you visualize your segmentation outputs?

### ISSUE THREAD

**Issue by hjsg1010** [WangYueFt/dgcnn#58]
Hi, I am impressed by your research and studying.
I have a question for visualizing your segmentation outputs.
I did some classification deeplearning models, but this is first time for segmentation.

I want to visualize outptus such as Figure6 and Figure 7  on your paper.

Did you use some tools such as MATLAB? 

And what should I use for input for visualize?

Sorry for my poor English skills.

Have a nice day

**Comment by hjsg1010** [comment]
and What effect did you expect by considering 'categorical vector'? 
I just wonder how you came up with this interesting idea.

**Comment by syb7573330** [comment]
Hi thanks for reaching out. We use Unity 3D for visualization. Simply put, the input is a point cloud, and each point is rendered as a sphere and colored according to its assigned semantic label.

**Comment by hjsg1010** [comment]
> Hi thanks for reaching out. We use Unity 3D for visualization. Simply put, the input is a point cloud, and each point is rendered as a sphere and colored according to its assigned semantic label.

@syb7573330 Oh Thanks for quick reply. I will try Unity program. Thankyou.
Also Can I get answer for above question? 
"and What effect did you expect by considering 'categorical vector'?
I just wonder how you came up with this interesting idea."
I am really curious and want to learn
