### ISSUE TITLE
How did you calculate forward time for several models?

### ISSUE THREAD

**Issue by hjsg1010** [WangYueFt/dgcnn#59]
Hi, first, sorry for keep asking about your research..

I'm curious about how to calculate forward time(or operation time?) for some models as shown at Table 3 on your paper.

And does that value means computational time for one epoch?

------------
and What effect did you expect by considering 'categorical vector'?
I just wonder how you came up with this interesting idea.

**Comment by WangYueFt** [comment]
Hi,

I think that's averaged by number of examples in each epoch. For your second question, I am not quite following the "categorical vector", is that the one we use in the segmentation pipeline?

**Comment by hjsg1010** [comment]
> is that the one we use in the segmentation pipeline?

@WangYueFt 
yes, in part_seg_code, it named as 'one_hot_label_expand'

**Comment by hjsg1010** [comment]
@WangYueFt 
"I think that's averaged by number of examples in each epoch."
This means that you divided the total learning time by total epoch?
Thx for Reply
