### ISSUE TITLE
Any idea of the get_edge_feature function for unknown batch size

### ISSUE THREAD

**Issue by leowang16** [WangYueFt/dgcnn#6]
Hi, thanks for your helpful code. But just one painful question: I would like to integrate your code into my Keras implementation. The function of get_edge_feature is using batch_size, which is 'None' for Keras (dynamic for any batch_size). Is it possible to generate the point_cloud_neighbors without using your solution (point_cloud is reshaped to (-1, num_dims)). I guess tf.scan could work. But I am still struggling with that. Many thanks!

**Comment by leowang16** [comment]
I think dynamic shape could solve that.
`batch_size = tf.shape(point_cloud)[0]`

**Comment by bach-zouk** [comment]
Hi,

@Lebo-Wang  Were you able to fix this issue? in Particular, can I decide batch size at run time and not a apriori?

Many thanks for your help

**Comment by leowang16** [comment]
batch_size = tf.shape(point_cloud)[0]
> Hi,
> 
> @Lebo-Wang Were you able to fix this issue? in Particular, can I decide batch size at run time and not a apriori?
> 
> Many thanks for your help
