### ISSUE TITLE
Why does the pytorch version not have transform？

### ISSUE THREAD

**Issue by sahalaan** [WangYueFt/dgcnn#77]
I cannot find the transform in pytorch version but can find it in tensorflow version. Can somebody find and note where the trasform in pytorch version is?  Thank you very much.

**Comment by bramton** [comment]
Duplicate of #32 

This repo has a nice PyTorch implementation of the spatial transform: https://github.com/AnTao97/dgcnn.pytorch

**Comment by sahalaan** [comment]
Accurate and perfect. Thank you!

**Comment by sahalaan** [comment]
> 

Accurate and perfect. Thank you!
