### ISSUE TITLE
Train seg & cls simultaneously

### ISSUE THREAD

**Issue by Salingo** [WangYueFt/dgcnn#9]
Hello,
I noticed that the architecture of your network has two branches for seg and cls, they split from the first edgeconv operation. In your code, I find the segmentation and classification are trained independently.
I wonder if there is a way to train seg and cls together with the different loss, just like Figure 3 shown in your paper?

**Comment by WangYueFt** [comment]
We actually trained them separately and I think you can do them together if you have a dataset which has both semantic labels and category labels.
